### ISSUE TITLE
Only working with a fresh diamond axe

### ISSUE THREAD

**Issue by gpisic** [DiscowZombie/LogRP#1]
It only works for me with a brand new diamond axe the first time and then stops working.
Also unbreakable diamond axes won't work.
Didn't try enchanted ones tho.

**Comment by DiscowZombie** [comment]
Hello,

It work for my... Which version of the plugin do you use ? What is your server version ?

**Comment by DiscowZombie** [comment]
Hello, your bug is now fixes! Download the new version **1.1.1** here: https://www.spigotmc.org/resources/logrp-break-trees-easy-mcmmo-style-opensource.32088/download?version=149095. Thank for report me this and have fun with LogRP.
