### ISSUE TITLE
Plugin not working at all after the latest update

### ISSUE THREAD

**Issue by gpisic** [DiscowZombie/LogRP#2]
Before it worked only with a completely new diamond axe. Now it doesn't work at all.

Spigot Version running: 1.11.2

Plugins: PermissionsEx, Voting, WorldEdit, PhantomAdmin, Herobrine, Vault, SaneEconomy, Quickshop

**Comment by DiscowZombie** [comment]
Hello,

I think you bug is fixes in this version: **v1.1.2**. You can download this here: https://www.spigotmc.org/resources/logrp-break-trees-easy-mcmmo-style-opensource.32088/download?version=149206. 

If your bug is fixes, don't forgot to lock this conversation, 

Thank you,
DiscowZombie.
