### ISSUE TITLE
No Tool Damage Toggle Setting

### ISSUE THREAD

**Issue by delixer** [DiscowZombie/LogRP#3]
Would it be possible to add a configuration variable to not apply any tool damage when chopping down trees?

**Comment by DiscowZombie** [comment]
Hi @delixer,

yes, good idea, I will work on :)

**Comment by DiscowZombie** [comment]
Added in the last update: https://www.spigotmc.org/resources/logrp-break-trees-easy-mcmmo-style-opensource-now-your-tools-lost-durability.32088/updates.

**Comment by delixer** [comment]
Thank you very much. I appreciate it. I would have made a fork myself but
it's been a long time since I have modded minecraft (pre-Bukkit DMCA) and
have no idea on how to setup my eclipse environment to make mods anymore :(


Thanks again.
Matt
